const offeringData = {
  '2115': { period: '1C_2026', enrolled: 73, professors: ['LARROSA, JUAN MANUEL CEFERINO'] },
  '3051': { period: '2C_2026', enrolled: 116, professors: ['GASANEO, GUSTAVO'] },
  '3058': { period: '2C_2026', enrolled: 72, professors: ['CARIATORE, NELSON DANIEL', 'CHIARADIA, DANIEL RAUL', 'PINCELLI, MICHELINA MARTA'] },
  '5523': { period: '1C_2026', enrolled: 180, professors: ['FILLOTTRANI, PABLO RUBEN'] },
  '5551': { period: '2C_2026', enrolled: 332, professors: ['BEL, ANDREA LILIANA', 'CAPRIOTTI, SANTIAGO', 'CARRIZO, GABRIEL ANIBAL', 'DE LEO, MARIANO FERNANDO', 'FERRANTE, BARBARA ISABEL', 'PANZONE, PABLO ANDRES', 'SLAGTER, JUAN SEBASTIÁN', 'SOLIS CARTAGENA, MARIEL PATRICIA'] },
  '5552': { period: '2C_2026', enrolled: 236, professors: ['ALZAGA, ALFREDO CARLOS', 'DIAZ VARELA, JOSE PATRICIO', 'EBERLE, MARIA GABRIELA', 'FERRANTE, BARBARA ISABEL', 'IGLESIAS, RODRIGO FERNANDO', 'NIEL, BLANCA ISABEL', 'PAOLINI, GRACIELA BEATRIZ', 'SLAGTER, JUAN SEBASTIÁN'] },
  '5561': { period: '1C_2026', enrolled: 181, professors: ['URRIBARRI, DANA KARINA'] },
  '5704': { period: '1C_2026', enrolled: 162, professors: ['FALAPPA, MARCELO ALEJANDRO'] },
  '5744': { period: '2C_2026', enrolled: 129, professors: ['MOYANO, JOSE HIPOLITO', 'STANKEVICIUS, ALEJANDRO GERMAN'] },
  '5793': { period: '2C_2026', enrolled: 188, professors: ['CARBALLIDO, JESSICA ANDREA', 'CECCHINI, ROCIO LUJAN', 'GARCIA, ALEJANDRO JAVIER', 'GARCIA, DIEGO RAMIRO'] },
  '5912': { period: '2C_2026', enrolled: 260, professors: ['CASTAÑO, DIEGO NICOLAS', 'CORNEJO, JUAN MANUEL', 'ENTIZNE, ROSANA VIRGINIA', 'FERRARO, SEBASTIAN JOSE', 'WAGNER, ROMINA TAMARA'] },
  '5949': { period: '2C_2026', enrolled: 194, professors: ['CENCI, KARINA MABEL'] },
  '6601': { period: '2C_2026', enrolled: 127, professors: ['HORST, MARIA FERNANDA', 'SPETTER, CARLA VANESA'] },
  '7527': { period: '1C_2026', enrolled: 114, professors: ['ESTEVEZ, ELSA CLARA'] },
  '7534': { period: '2C_2026', enrolled: 73, professors: ['ENDARA, MARCELO JAVIER'] },
  '7552': { period: '2C_2026', enrolled: 100, professors: ['FALAPPA, MARCELO ALEJANDRO', 'VITTURINI, MARIA MERCEDES'] },
  '7655': { period: '2C_2026', enrolled: 103, professors: ['GOMEZ, SERGIO ALEJANDRO', 'LARREA, MARTIN LEONARDO', 'NICOLINI, ANA LUCIA', 'SOTO, AXEL JUAN'] },
  '7668': { period: '1C_2026', enrolled: 65, professors: ['SIMARI, GERARDO IGNACIO'] },
  '7680': { period: null, enrolled: null, professors: [] },
  '7713': { period: '2C_2026', enrolled: 146, professors: ['GANUZA, MARIA LUJAN', 'TAMARGO, LUCIANO HECTOR'] },
  '7714': { period: '2C_2026', enrolled: 197, professors: ['CASALINI, MARIA CLARA', 'SOTO, AXEL JUAN'] },
  '7791': { period: '2C_2026', enrolled: 157, professors: ['DELLADIO, TELMA', 'MAGUITMAN, ANA GABRIELA'] },
  '7811': { period: null, enrolled: null, professors: [] },
  '7820': { period: '2C_2026', enrolled: 147, professors: ['PISTONESI, SILVINA'] },
  '7821': { period: '2C_2026', enrolled: 106, professors: ['COBO, MARIA LAURA', 'DELLADIO, TELMA'] },
  '7891': { period: '2C_2026', enrolled: 101, professors: ['SIMARI, GERARDO IGNACIO'] },
  '7903': { period: '1C_2026', enrolled: 99, professors: ['STANKEVICIUS, ALEJANDRO GERMAN'] },
  '7911': { period: '1C_2026', enrolled: 111, professors: ['CABRERA SOTO, FABIAN ARIEL', 'COHEN, ANDREA'] },
  '7922': { period: '2C_2026', enrolled: 98, professors: ['COHEN, ANDREA'] },
  '7949': { period: '2C_2026', enrolled: 110, professors: ['CHESÑEVAR, CARLOS IVAN'] },
  '7951': { period: '2C_2026', enrolled: 98, professors: ['JOAQUÍN, FEDERICO'] },
  '7993': { period: '2C_2026', enrolled: 102, professors: ['LARREA, MARTIN LEONARDO'] },
};
